export * from './Layout.component'
// export * from './TabBar.component'
// export * from './Loading.component'
// export * from './Module.component'
export { default as Layout } from './Layout.component'
// export { default as ErrorBoundary } from './ErrorBoundary'

export * from './Report1.component'
export * from './Process1.component'
export * from './Home.component'