# This is a basic workflow to help you get started with Actions

name: GITHUB_ACTIONS_CICD_TALK

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    env: 
      PKG_NAME_1: ${{ format('real-value-app-0.1.0.{0}.tgz', github.run_number) }}
      PKG_NAME: $( echo "real-value-app-0.1.0.$GITHUB_RUN_NUMBER.tgz" )

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'

    - name: Inspect
      run: echo $PKG_NAME
            
    - name: Check variables
      run: echo $GITHUB_RUN_NUMBER $PKG_NAME
        
    - name: Build and Test
      run: |
        npm install
        npm test

    - name: Package
      run: $( echo 'tar czf $PKG_NAME src node_modules package.json lib public' )
     
    - uses: actions/upload-artifact@v2
      with:
        name: $( echo PKG_NAME )
        path: $( echo PKG_NAME )
