# This is a basic workflow to help you get started with Actions

name: GITHUB_ACTIONS_CICD_TALK

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env: 
      PKG_NAME: "real-value-app-0.1.0.$GITHUB_RUN_NUMBER.tgz"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'

    - name: Inspect
      run: echo $PKG_NAME
    
    # - name: Set Variables
    #   run: |
    #     echo ::set-env PKG_NAME=real-value-app-0.1.0.${{GITHUB_RUN_NUMBER}}.tgz
        
    - name: Check variables
      run: echo $GITHUB_RUN_NUMBER $PKG_NAME
        

    # Build and Test
    - name: Run a multi-line script
      run: |
        npm install
        npm test
    
    - name: Package
      run: tar czf real-value-app-0.1.0.$GITHUB_RUN_NUMBER.tgz src node_modules package.json lib public

    - uses: actions/upload-artifact@v2
      with:
        name: real-value-app.0.1.0.$GITHUB_RUN_NUMBER.tgz
        path: real-value-app.0.1.0.$GITHUB_RUN_NUMBER.tgz